### ISSUE TITLE
[REQ] Allow multiple locations

### ISSUE THREAD

**Issue by NullDivision** [larsonjj/grunt-flow#3]
It seems a bit wrong to have flow only execute in the root directory. Wouldn't it make more sense to be able to direct the Grunt config to the location where the `.flowconfig` file is and have it execute there?

**Comment by larsonjj** [comment]
@NullDivision,

Sorry for the late response. `.flowconfig` file is normally put into the root folder of a project along with the `Gruntfile.js`. Not sure what the use case would be where that would not be the case. If you would like to conditionalize which files/folders are read by flow you can read more about that in the [[include] Flow Docs](http://flowtype.org/docs/advanced-configuration.html).
